edge_id_separator = '___'
saved_node_attribute_list = ['notes', 'annotation', 'source', '_nodetype']
saved_edge_attribute_list = ['weight', 'notes', 'annotation']
saved_network_attribute_list = ['notes', 'annotation']

# There is a web page that gives the list of correct `database identifiers
#  <http://www.uniprot.org/faq/28>

# ID mapping options from bioservoces.uniprot
# These are made available in parameters.py to 
# tie the rest of NAMpy together
available_mapping_target = {"UniProtKB ACC": "ACC",
               "UniProtKB ID": "ID",
               "UniParc": "UPARC",
               "UniRef50": "NF50",
               "UniRef90": "NF90",
               "UniRef100": "NF100",
               "EMBL/GenBank/DDBJ": "EMBL_ID",
               "EMBL/GenBank/DDBJ CDS": "EMBL",
               "PIR": "PIR",
               "UniGene": "UNIGENE_ID",
               "Entrez Gene (GeneID)": "P_ENTREZGENEID",
               "GI number*":"P_GI", 
               "IPI": "P_IPI",
               "RefSeq Protein": "P_REFSEQ_AC",
               "RefSeq Nucleotide": "REFSEQ_NT_ID",
               "PDB": "PDB_ID",
               "DisProt": "DISPROT_ID",
               "HSSP": "HSSP_ID",
               "DIP": "DIP_ID",
               "MINT": "MINT_ID",
               "Allergome": "ALLERGOME_ID",
               "MEROPS": "MEROPS_ID",
               "mycoCLAP": "MYCOCLAP_ID",
               "PeroxiBase": "PEROXIBASE_ID",
               "PptaseDB": "PPTASEDB_ID",
               "REBASE": "REBASE_ID",
               "TCDB": "TCDB_ID",
               "PhosSite": "PHOSSITE_ID",
               "DMDM": "DMDM_ID",
               "Aarhus/Ghent-2DPAGE": "AARHUS_GHENT_2DPAGE_ID",
               "World-2DPAGE": "WORLD_2DPAGE_ID",
               "DNASU": "DNASU_ID",
               "Ensembl": "ENSEMBL_ID",
               "Ensembl Protein": "ENSEMBL_PRO_ID",
               "Ensembl Transcript": "ENSEMBL_TRS_ID",
               "Ensembl Genomes": "ENSEMBLGENOME_ID",
               "Ensembl Genomes Protein": "ENSEMBLGENOME_PRO_ID",
               "Ensembl Genomes Transcript": "ENSEMBLGENOME_TRS_ID",
               "GeneID": "P_ENTREZGENEID",
               "GenomeReviews": "GENOMEREVIEWS_ID",
               "KEGG": "KEGG_ID",
               "PATRIC": "PATRIC_ID",
               "UCSC": "UCSC_ID",
               "VectorBase": "VECTORBASE_ID",
               "AGD": "AGD_ID",
               "ArachnoServer": "ARACHNOSERVER_ID",
               "CGD": "CGD",
               "ConoServer": "CONOSERVER_ID",
               "CYGD": "CYGD_ID",
               "dictyBase": "DICTYBASE_ID",
               "EchoBASE": "ECHOBASE_ID",
               "EcoGene": "ECOGENE_ID",
               "euHCVdb": "EUHCVDB_ID",
               "EuPathDB": "EUPATHDB_ID",
               "FlyBase": "FLYBASE_ID",
               "GeneCards": "GENECARDS_ID",
               "GeneFarm": "GENEFARM_ID",
               "GenoList": "GENOLIST_ID",
               "H-InvDB": "H_INVDB_ID",
               "HGNC": "HGNC_ID",
               "HPA": "HPA_ID",
               "LegioList": "LEGIOLIST_ID",
               "Leproma": "LEPROMA_ID",
               "MaizeGDB": "MAIZEGDB_ID",
               "MIM": "MIM_ID",
               "MGI": "MGI_ID",
               "neXtProt": "NEXTPROT_ID",
               "Orphanet": "ORPHANET_ID",
               "PharmGKB": "PHARMGKB_ID",
               "PomBase": "POMBASE_ID",
               "PseudoCAP": "PSEUDOCAP_ID",
               "RGD": "RGD_ID",
               "SGD": "SGD_ID",
               "TAIR": "TAIR_ID",
               "TubercuList": "TUBERCULIST_ID",
               "WormBase": "WORMBASE_ID",
               "WormBase Transcript": "WORMBASE_TRS_ID",
               "WormBase Protein": "WORMBASE_PRO_ID",
               "Xenbase": "XENBASE_ID",
               "ZFIN": "ZFIN_ID",
               "eggNOG": "EGGNOG_ID",
               "GeneTree": "GENETREE_ID",
               "HOGENOM": "HOGENOM_ID",
               "HOVERGEN": "HOVERGEN_ID",
               "KO": "KO_ID",
               "OMA": "OMA_ID",
               "OrthoDB": "ORTHODB_ID",
               "ProtClustDB": "PROTCLUSTDB_ID",
               "BioCyc": "BIOCYC_ID",
               "Reactome": "REACTOME_ID",
               "UniPathWay": "UNIPATHWAY_ID",
               "CleanEx": "CLEANEX_ID",
               "GermOnline": "GERMONLINE_ID",
               "ChEMBL": "CHEMBL_ID",
               "ChiTaRS": "CHITARS_ID",
               "DrugBank": "DRUGBANK_ID",
               "GenomeRNAi": "GENOMERNAI_ID",
               "NextBio": "NEXTBIO_ID"}

available_mapping_source = {"UniProtKB ACC/ID": "ACC+ID",
               "UniParc": "UPARC",
               "UniRef50": "NF50",
               "UniRef90": "NF90",
               "UniRef100": "NF100",
               "EMBL/GenBank/DDBJ": "EMBL_ID",
               "EMBL/GenBank/DDBJ CDS": "EMBL",
               "PIR": "PIR",
               "UniGene": "UNIGENE_ID",
               "Entrez Gene (GeneID)": "P_ENTREZGENEID",
               "GI number*":"P_GI", 
               "IPI": "P_IPI",
               "RefSeq Protein": "P_REFSEQ_AC",
               "RefSeq Nucleotide": "REFSEQ_NT_ID",
               "PDB": "PDB_ID",
               "DisProt": "DISPROT_ID",
               "HSSP": "HSSP_ID",
               "DIP": "DIP_ID",
               "MINT": "MINT_ID",
               "Allergome": "ALLERGOME_ID",
               "MEROPS": "MEROPS_ID",
               "mycoCLAP": "MYCOCLAP_ID",
               "PeroxiBase": "PEROXIBASE_ID",
               "PptaseDB": "PPTASEDB_ID",
               "REBASE": "REBASE_ID",
               "TCDB": "TCDB_ID",
               "PhosSite": "PHOSSITE_ID",
               "DMDM": "DMDM_ID",
               "Aarhus/Ghent-2DPAGE": "AARHUS_GHENT_2DPAGE_ID",
               "World-2DPAGE": "WORLD_2DPAGE_ID",
               "DNASU": "DNASU_ID",
               "Ensembl": "ENSEMBL_ID",
               "Ensembl Protein": "ENSEMBL_PRO_ID",
               "Ensembl Transcript": "ENSEMBL_TRS_ID",
               "Ensembl Genomes": "ENSEMBLGENOME_ID",
               "Ensembl Genomes Protein": "ENSEMBLGENOME_PRO_ID",
               "Ensembl Genomes Transcript": "ENSEMBLGENOME_TRS_ID",
               "GeneID": "P_ENTREZGENEID",
               "GenomeReviews": "GENOMEREVIEWS_ID",
               "KEGG": "KEGG_ID",
               "PATRIC": "PATRIC_ID",
               "UCSC": "UCSC_ID",
               "VectorBase": "VECTORBASE_ID",
               "AGD": "AGD_ID",
               "ArachnoServer": "ARACHNOSERVER_ID",
               "CGD": "CGD",
               "ConoServer": "CONOSERVER_ID",
               "CYGD": "CYGD_ID",
               "dictyBase": "DICTYBASE_ID",
               "EchoBASE": "ECHOBASE_ID",
               "EcoGene": "ECOGENE_ID",
               "euHCVdb": "EUHCVDB_ID",
               "EuPathDB": "EUPATHDB_ID",
               "FlyBase": "FLYBASE_ID",
               "GeneCards": "GENECARDS_ID",
               "GeneFarm": "GENEFARM_ID",
               "GenoList": "GENOLIST_ID",
               "H-InvDB": "H_INVDB_ID",
               "HGNC": "HGNC_ID",
               "HPA": "HPA_ID",
               "LegioList": "LEGIOLIST_ID",
               "Leproma": "LEPROMA_ID",
               "MaizeGDB": "MAIZEGDB_ID",
               "MIM": "MIM_ID",
               "MGI": "MGI_ID",
               "neXtProt": "NEXTPROT_ID",
               "Orphanet": "ORPHANET_ID",
               "PharmGKB": "PHARMGKB_ID",
               "PomBase": "POMBASE_ID",
               "PseudoCAP": "PSEUDOCAP_ID",
               "RGD": "RGD_ID",
               "SGD": "SGD_ID",
               "TAIR": "TAIR_ID",
               "TubercuList": "TUBERCULIST_ID",
               "WormBase": "WORMBASE_ID",
               "WormBase Transcript": "WORMBASE_TRS_ID",
               "WormBase Protein": "WORMBASE_PRO_ID",
               "Xenbase": "XENBASE_ID",
               "ZFIN": "ZFIN_ID",
               "eggNOG": "EGGNOG_ID",
               "GeneTree": "GENETREE_ID",
               "HOGENOM": "HOGENOM_ID",
               "HOVERGEN": "HOVERGEN_ID",
               "KO": "KO_ID",
               "OMA": "OMA_ID",
               "OrthoDB": "ORTHODB_ID",
               "ProtClustDB": "PROTCLUSTDB_ID",
               "BioCyc": "BIOCYC_ID",
               "Reactome": "REACTOME_ID",
               "UniPathWay": "UNIPATHWAY_ID",
               "CleanEx": "CLEANEX_ID",
               "GermOnline": "GERMONLINE_ID",
               "ChEMBL": "CHEMBL_ID",
               "ChiTaRS": "CHITARS_ID",
               "DrugBank": "DRUGBANK_ID",
               "GenomeRNAi": "GENOMERNAI_ID",
               "NextBio": "NEXTBIO_ID"}
